
import { ToastContainer } from 'react-toastify'
import { LanguageProvider } from '../components/languageContext'
import  LayoutDecider  from '../components/Layout/LayoutDecider';
import { ThemeWrapper } from '@/components/ThemeWrapper';
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: '',
    description: ' Generated by Torus'
  }

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <LanguageProvider>
      <div className=' relative h-[100vh] w-[100vw]  overflow-hidden'>
        <ThemeWrapper>
          <LayoutDecider
            mode='detached' 
            navigationStyles='vertical' 
            sidebarStyle='compact'
          >
            <main className="h-full w-full">{children}</main>
            <ToastContainer />
          </LayoutDecider>
        </ThemeWrapper>
      </div>
    </LanguageProvider>
  )
}
