apiVersion: v1
kind: Pod
metadata:
  name: buildah-agent
  namespace: devops-tools
spec:
  hostAliases:
  - ip: "192.168.2.190"
    hostnames:
    - "lb.kubesphere.local"
  containers:
    - name: buildah
      image: 192.168.2.164:5000/buildah-git-pki:v2
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: buildah-cache
          mountPath: /var/lib/containers
        - name: registry-creds
          mountPath: /home/buildah/.docker
          readOnly: true
  volumes:
    - name: buildah-cache
      persistentVolumeClaim:
        claimName: buildah-cache-pvc
    - name: registry-creds
      secret:
        secretName: buildah-registry-creds
  restartPolicy: Always
