pipeline {
    agent {
        label 'slave-32'
    }
    tools {
        jdk 'jdk17' 
        nodejs 'Node20.0.0'
    }
    environment {
        DOCKERHUB_USERNAME = "192.168.2.34:5000"
        APP_NAME = "ct001-tgw004-uf-v1"
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/${APP_NAME}"
        BUILD_NUMBER = "${BUILD_NUMBER}"
        GITHUB_CREDENTIALS = "GIT_HUB_PAT"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    triggers {
        githubPush() 
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Code Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${GITHUB_CREDENTIALS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    git branch: 'master', credentialsId: "${GITHUB_CREDENTIALS}", url: 'https://github.com/TorusDev2023/Claims5UF.git'
                }
            }
        }

        stage('Detect Changes in CT001 App') {
            steps {
                script {
                    def diff = sh(script: "git diff --name-only HEAD~1 HEAD", returnStdout: true).trim()
                    if (diff.split('\n').any { it.startsWith('apps/CT001/TGW01/TGW004/v1/Next-uf/') }) {
                        env.NEXT_UF_CHANGED = "true"
                        echo "Changes detected in apps/CT001/TGW01/TGW004/v1/Next-uf"
                    } else {
                        env.NEXT_UF_CHANGED = "false"
                        echo "No changes in apps/CT001/TGW01/TGW004/v1/Next-uf. Skipping build and deployment stages."
                    }
                }
            }
        }

        stage('Docker Build & Push') {
            when {
                expression { return env.NEXT_UF_CHANGED == "true" }
            }
            steps {
                script {
                    sh """
                    export DOCKER_BUILDKIT=1
                    docker buildx use default
                    
                    docker buildx build \
                        --build-arg BUILDKIT_INLINE_CACHE=1 \
                        --tag ${IMAGE_NAME}:${IMAGE_TAG} \
                        --file apps/CT001/TGW01/TGW004/v1/Next-uf/Dockerfile \
                        apps/CT001/TGW01/TGW004/v1/Next-uf \
                        --push
  """
                }
            }
        }

        stage('Update Kubernetes Deployment File') {
            when {
                expression { return env.NEXT_UF_CHANGED == "true" }
            }
            steps {
                script {
                    sh "sed -i 's/docker_tag/${IMAGE_TAG}/g' apps/CT001/TGW01/TGW004/v1/Next-uf/kubernetes/deploymentservice.yaml"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            when {
                expression { return env.NEXT_UF_CHANGED == "true" }
            }
            steps {
                script {
                    withKubeConfig(credentialsId: 'kubernetes-32', serverUrl: 'https://lb.kubesphere.local:6443') {
                        sh "kubectl get ns ct001-tgw004-uf-v1 || kubectl create ns ct001-tgw004-uf-v1"
                        sh "kubectl apply -f apps/CT001/TGW01/TGW004/v1/Next-uf/kubernetes/deploymentservice.yaml"
                        sh "kubectl apply -f apps/CT001/TGW01/TGW004/v1/Next-uf/kubernetes/gateway-uf-ingress.yaml"
                    }
                }
            }
        }

        stage('Remove Previous Build Image') {
            when {
                expression { return env.NEXT_UF_CHANGED == "true" }
            }
            steps {
                script {
                    def prevBuildNumber = env.BUILD_NUMBER.toInteger() - 1
                    if (prevBuildNumber > 0) {
                        sh "docker rmi -f ${IMAGE_NAME}:${prevBuildNumber} || true"
                    }
                }
            }
        }
    }
}